version: "3.3"
services:

  backend:
    image: 'sql_convert_backend_test:latest'
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    ports:
      - "8000:8000"
    entrypoint: 
      - pytest
