name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: test env
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: ${{ secrets.TARGET_DIR }}
      run: |
        echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
        sudo ssh -o StrictHostKeyChecking=no -i private_key ${REMOTE_USER}@${REMOTE_HOST} '
            # Now we have got the access of EC2 and we will start the deploy .
            cd /home/ubuntu &&
            rm -rf ./sql_convert_app &&
            git clone https://github.com/Niwaiwa/sql_convert_app.git
            cd sql_convert_app &&
            sudo docker-compose down --rmi all --volumes --remove-orphans &&
            sudo docker-compose up -d --build
              '
          # cd /home/ubuntu
          # rm -rf ./sql_convert_app
          # git clone https://github.com/Niwaiwa/sql_convert_app.git
          # cd sql_convert_app
          # docker-compose down --rmi all --volumes --remove-orphans
          # docker-compose up -d --build
